### ISSUE TITLE
MacOSX

### ISSUE THREAD

**Issue by OniDaito** [Jonty/Idiocy#1]
Not sure about this. pcapy has a different module name and different functions (though many remain the same). Tried the macosx install of pcapy and had no joy sadly. Will continue though.

**Comment by Jonty** [comment]
Whoops, I meant python-pcap/pypcap. Updated the readme and added a link.

Sorry!

**Comment by OniDaito** [comment]
Hehehe, no worries. On OSX Snow Leopard, system python is 2.7 by default I think so pypcap don't like it (2.5 apparently... cant be arsed changing system python) so I might look at doing it with 2.7
