### ISSUE TITLE
ubuntu 10.04 errors

### ISSUE THREAD

**Issue by ghost** [Jonty/Idiocy#3]
Hi. I'm not sure what I'm doing but I hope that my errors can help someone out. I'm still googling around to try to solve them but no luck.  I did read the readme. 

$ sudo apt-get install libpcap python-pcap python-dpkt
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Couldn't find package libpcap
$ 

$ sudo iw wlan0 interface add mon0 type monitor && ifconfig mon0 up
SIOCSIFFLAGS: Permission denied
$ 

:~/Documents/Jonty-Idiocy-80d8bd1$ ls
idiocy.py  README.md
:~/Documents/Jonty-Idiocy-80d8bd1$ ./idiocy.py -i mon0
bash: ./idiocy.py: Permission denied
~/Documents/Jonty-Idiocy-80d8bd1$ sudo ./idiocy.py -i mon0
sudo: ./idiocy.py: command not found

~/Documents/Jonty-Idiocy-80d8bd1$ python idiocy.py 
Traceback (most recent call last):
 File "idiocy.py", line 2, in <module>
 import getopt, sys, pcap, dpkt, re, httplib, urllib
ImportError: No module named pcap
~/Documents/Jonty-Idiocy-80d8bd1$ 

My questions are: 
1. how do I install libpcap? 
2. How can I get around the "SIOCSIFFLAGS: Permission denied" problem? 
3. I'm making a basic error with the " ./idiocy.py -i mon0 " but I don't know what it is. Please hint? 
4. Why is pcap missing and where can I find it?

**Comment by josephtannenbaum** [comment]
the pcap apparently comes from here: code.google.com/p/pypcap

but the install.py in the source tarball is useless. Errors everywhere.

**Comment by mrenouf** [comment]
1. apt-get install python-pypcap
2. sudo - you need to be root silly
3. See 2
4. See 1

**Comment by Jonty** [comment]
I've updated the readme to have the correct package names, sorry about that!

**Comment by ghost** [comment]
Royall, tweakt, many thanks. You've helped me get new errors. Jonty, thanks for the update. This is a cool thing you've made.

$ sudo iw wlan0 interface add mon0 type monitor && ifconfig mon0 up
command failed: Too many open files in system (-23)
$

What I've tried: 
rebooting and trying again immediately after boot. (wireless hard switch on and off.) no luck. 

$ cat /proc/sys/fs/file-max
 252358

dmesg and lsof both give me a giant pile of output which makes no sense (to me). 

to find how many open files there are  
   $ sudo lsof | wc -l
   lsof: WARNING: can't stat() fuse.gvfs-fuse-daemon file system /home/geeklinda/.gvfs 
Output information may be incomplete.
   ^C
  $ 

without sudo
$ python idiocy.py -i mon0
Traceback (most recent call last):
  File "idiocy.py", line 128, in <module>
    main()
  File "idiocy.py", line 20, in main
    cap = pcap.pcap(device)
  File "pcap.pyx", line 194, in pcap.pcap.**init**
OSError: no suitable device found

with sudo
$ sudo python idiocy.py -i mon0
at this point it hangs and does nothing in terminal. I gave it an unsecured twitter account to access (my own) but nothing happened. See below.     

geeklinda@cyberpunk-geeklinda:~/Documents/Jonty-Idiocy-80d8bd1$ sudo python idiocy.py -i mon0
^C
Traceback (most recent call last):
  File "idiocy.py", line 128, in <module>
    main()
  File "idiocy.py", line 25, in main
    for ts, raw in cap:
  File "pcap.pyx", line 425, in pcap.pcap.**next**
KeyboardInterrupt
$ 

My new questions are: 
5. Do you think the "too many open files" error a symptom of something wrong in my system (possible; I've been fiddling locally), or just an error because of some missing package that is being called, or... ? 
6. Given that I'm not a python person, what's going on in that traceback? As far as I know, there's no line 425 in idiocy.py. Am I missing a file? What kind of fix should I be trying? 

Also, sorry about the formatting above. The flavored markdown is gah.
