### ISSUE TITLE
Variable name

### ISSUE THREAD

**Issue by tewson** [Jonty/Idiocy#4]
Idiocy is impressive. However before I could run it I needed to modify it a bit.

Shouldn't line #16 be "device = a" instead? I changed to that and it works just fine.

**Comment by Jonty** [comment]
Whoops, I hadn't committed that change, meaning it would use the first device it found...

Thanks for the heads up. Fix pushed.

**Comment by tewson** [comment]
Thanks for a fast response, too! :)
